package grafic;

import java.util.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.event.*;
import liceu.*;

public class PanouListaMaterii extends javax.swing.JPanel implements
        ListSelectionListener
{

    private JButton adauga, sterge;
    private Profesor profesorSelectat;
    private ArrayList<Materie> listaMaterii;
    private ListenerAdaugaMaterie listenerAdauga;
    private ListenerStergeMaterie listenerSterge;

    public PanouListaMaterii()
    {
        initComponents();
        
        adauga = new JButton("Adăugaţi");
        listenerAdauga = new ListenerAdaugaMaterie(jList1, adauga);
        adauga.addActionListener(listenerAdauga);
        adauga.setEnabled(false);
        sterge = new JButton("Ştergeţi");
        
        listenerSterge = new ListenerStergeMaterie(jList1);
        sterge.addActionListener(listenerSterge);
        sterge.setEnabled(false);
        jPanel1.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = c.gridy = 0;
        c.insets = new Insets(0, 0, 0, 3);
        jPanel1.add(adauga, c);
        c.gridx = 1;
        c.insets = new Insets(0, 3, 0, 1);
        jPanel1.add(sterge, c);
        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(this);
    }
    
    // dupa ce s-a selectat un profesor
    public void activeaza(Profesor prof)
    {
        profesorSelectat = prof;
        listaMaterii = new ArrayList<Materie>();
        for (Iterator<Materie> i = prof.iteratorMaterii(); i.hasNext(); )
            listaMaterii.add(i.next());

        jLabel1.setEnabled(true);
        jScrollPane1.setEnabled(true);
        jList1.setEnabled(true);
        sterge.setEnabled(false);
        DefaultListModel modelLista = new DefaultListModel();
        for (Iterator<Materie> i = listaMaterii.iterator(); i.hasNext(); )
            modelLista.addElement(i.next().getNume());
        jList1.setModel(modelLista);

        // daca profesorul preda deja toate materiile
        if (listaMaterii.size() == Centralizator.getInstance().getDictionar().
                keySet().size())
            adauga.setEnabled(false);
        else
        {
            adauga.setEnabled(true);
            listenerAdauga.setMaterii(listaMaterii);
        }
        PanouEditeazaMaterii pem = (PanouEditeazaMaterii)(getParent().
                getParent());
        Secretar secretar = (Secretar)((Fereastra)SwingUtilities.
                getWindowAncestor(this)).getUtilizatorLogat();
        listenerSterge.setDate(listaMaterii, profesorSelectat, secretar, pem);

        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public JButton getSterge()
    {
        return sterge;
    }
    
    public void valueChanged(ListSelectionEvent e)
    {
        if (e.getValueIsAdjusting() == false && jList1.getSelectedIndex() != -1)
        {
            sterge.setEnabled(true);
            PanouEditeazaMaterii pem = (PanouEditeazaMaterii)(getParent().
                    getParent());
            JPanel pcb = pem.getPanouChecks().getPanouPropriuZis();
            Component[] componente = pcb.getComponents();
            for (int i = 0; i < componente.length; ++i)
                pcb.remove(componente[i]);
            pcb.setLayout(new BoxLayout(pcb, BoxLayout.PAGE_AXIS));
            for (Iterator<Clasa> i = pem.iteratorClase(); i.hasNext(); )
            {
                Clasa clasa = i.next();
                JCheckBox cb = new JCheckBox(clasa.getId());
                pcb.add(cb);
                HashMap<Materie, HashMap<Clasa, Profesor>> d =
                        Centralizator.getInstance().getDictionar();
                Materie materie = listaMaterii.get(jList1.getSelectedIndex());
                if (d.get(materie).get(clasa) == profesorSelectat)
                    cb.setSelected(true);
                cb.addActionListener(new ListenerCheckBox(profesorSelectat,
                        materie, clasa));
            }
            pcb.revalidate();
            pcb.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setEnabled(false);

        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jLabel1.setText("Materii predate:");
        jLabel1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
