package grafic;

import java.util.*;
import java.awt.*;
import javax.swing.*;
import liceu.*;

public class PanouEditeazaMaterii extends javax.swing.JPanel
{
    private Profesor profesorSelectat;
    private Vector<String> comboVect;
    private DefaultComboBoxModel comboModel;
    private JList listaMaterii;
    private PanouCheckBoxes panouChecks;
    private PanouListaMaterii panouMateriiButoane;
    private ArrayList<Clasa> toateClasele;
    
    public PanouEditeazaMaterii()
    {
        initComponents();
        comboVect = new Vector<String>();
        
        ArrayList<Profesor> profi;
        for (Iterator<Profesor> i = Centralizator.getInstance().
                iteratorProfesori(); i.hasNext(); )
        {
            Profesor prof = i.next();
            comboVect.add(prof.getPrenume() + " " + prof.getNume());
        }
        comboVect.insertElementAt("Selectaţi un profesor", 0);
        
        comboModel = new DefaultComboBoxModel(comboVect);
        jComboBox1.setModel(comboModel);
        
        toateClasele = new ArrayList<Clasa>();
        Centralizator centralizator = Centralizator.getInstance();
        for (Iterator<Clasa> i = centralizator.getClase(null).iterator();
                i.hasNext(); )
            toateClasele.add(i.next());
        
        jPanel1.setLayout(new GridLayout(1, 2, 5, 0));
        panouMateriiButoane = new PanouListaMaterii();
        jPanel1.add(panouMateriiButoane);
        panouChecks = new PanouCheckBoxes();
        jPanel1.add(panouChecks);
    }
    
    public Iterator<Clasa> iteratorClase()
    {
        return toateClasele.iterator();
    }
    
    public PanouCheckBoxes getPanouChecks()
    {
        return panouChecks;
    }
    
    public PanouListaMaterii getPanouListaMaterii()
    {
        return panouMateriiButoane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, 380, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().equals("Selectaţi un profesor"))
            return;

        Object selectat = comboModel.getSelectedItem();
        if (comboVect.elementAt(0).equals("Selectaţi un profesor"))
        {
            comboVect.remove(0);
            comboModel = new DefaultComboBoxModel(comboVect);
            comboModel.setSelectedItem(selectat);
            jComboBox1.setModel(comboModel);
        }
        
        int index = 0, indexSelectat = jComboBox1.getSelectedIndex();
        for (Iterator<Profesor> i = Centralizator.getInstance().
                iteratorProfesori(); i.hasNext(); ++index)
        {
            Profesor profesorCurent = i.next();
            if (index == indexSelectat)
            {
                profesorSelectat = profesorCurent;
                break;
            }
        }
        panouMateriiButoane.activeaza(profesorSelectat);
        panouChecks.activeaza();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
